name: Publish Pipeline

run-name: |
  Publish pipeline to Artifactory

on:
  workflow_dispatch:
    inputs:
      delivery_file:
        type: string
        description: Delivery file
        required: true
        default: ""

      unbuffered:
        type: boolean
        description: Disable line buffering
        default: true

      verbose:
        type: boolean
        description: Toggle verbose output
        default: false

      continue_on_error:
        type: boolean
        description: Allow tests to fail
        default: false

      no_testing:
        type: boolean
        description: Disable all tests
        default: false

      no_artifactory:
        type: boolean
        description: Disable Artifactory (including existence checks)
        default: false

      no_artifactory_upload:
        type: boolean
        description: Disable Artifactory deployment (excluding existence checks)
        default: false

      no_docker:
        type: boolean
        description: Disable Docker image building
        default: false

      stasis_args:
        type: string
        description: Custom arguments to pass to STASIS
        required: false
        default: ""

jobs:
  publish:
    name: Publish
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      #- name: Mount data area
      #  uses: ./.github/actions/sshfs
      #  with:
      #    user: ${{ secrets.SVC_SSHFS_USER }}
      #    password: ${{ secrets.SVC_SSHFS_PASS }}
      #    remote_host: example.tld
      #    remote_dir: /data
      #    local_dir: /mydata

      - name: STASIS (${{ runner.os }}-${{ runner.arch }})
        uses: ./.github/actions/stasis
        with:
          prefix: ${{ github.workspace }}/.local
          artifactory_url: https://blah.tld
          artifactory_repo: ${{ inputs.artifactory_repo }}
          stasis_args: ${{ inputs.stasis_args }}
          option_delivery_file: ${{ inputs.delivery_file }}
          option_verbose: ${{ inputs.verbose }}
          option_continue_on_error: ${{ inputs.continue_on_error }}
          option_no_testing: ${{ inputs.no_testing }}
          option_no_artifactory: ${{ inputs.no_artifactory }}
          option_no_artifactory_upload: ${{ inputs.no_artifactory_upload }}
          option_no_docker: ${{ inputs.no_docker }}
          option_unbuffered: ${{ inputs.unbuffered }}

