name: Deliver Pipeline

run-name: |
  Deliver Pipeline

on:
  workflow_dispatch:
    inputs:
      artifactory_repo:
        type: string
        description: Artifactory repository path where deliveries are stored
        required: true
        default: "some-repo"

      mission:
        type: choice
        description: Mission name (e.g. hst)
        options:
          - thing1
          - thing2
          - thing3
          - thing4
        required: true
        default: "thing4"

      build_name:
        type: string
        description: Build name (e.g. MYPIPELINE-1.2.3)
        requires: true
        default: ""

      destination:
        type: string
        description: Path to store an indexed delivery
        required: true
        default: "/path/to/stasis/releases"

      stasis_indexer_args:
        type: string
        description: arguments for stasis tool
        required: true
        default: ""

jobs:
  deliver:
    name: Deliver
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Index
        uses: ./.github/actions/stasis_indexer
        with:
          artifactory_repo: ${{ inputs.artifactory_repo }}
          mission: ${{ inputs.mission }}
          build_name: ${{ inputs.build_name }}
          destination: ${{ inputs.destination }}
          stasis_indexer_args: ${{ inputs.stasis_indexer_args }}

